name: Publish to npm

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the 'main' branch
    tags:
      - 'v*'  # Trigger when a new version tag is pushed (e.g., v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the appropriate version of Node.js
        registry-url: 'https://registry.npmjs.org/'

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Log in to npm
    - name: Authenticate to npm
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org/'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Use the npm token stored in GitHub Secrets

    # Publish to npm
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Ensure authentication for publishing
